sudo: required
services: 
    - docker
language: generic 

before_install:
    - docker build -t volodymyrfalendysh/docker-react -f Dockerfile.dev .

script:
    - docker run volodymyrfalendysh/docker-react npm run test -- --coverage